name: Deploy to Dev

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Deploy to Dev'
        # Input has to be provided for the workflow to run
        required: false

# Disabling on-push trigger - as GH action service is degraded right now
# on:
#   push:
#      branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Nginx configuration
        run: sudo nginx -t
      - name: Copy index.html to nginx docs
        run: sudo rm -rf /var/www/html/index.html && sudo cp ${{ github.workspace }}/index.html /var/www/html/
      - name: Restart nginx service
        run: sudo systemctl restart nginx
