name: Deploy to Dev
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Nginx configuration
        run: sudo nginx -t
