name: Deploy to Dev

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate Nginx configuration
        run: sudo nginx -t
